"""Exact computation of b_r(d) = max kappa(S(t,zeta)) over t in T, zeta primitive r-th root.
See README.md for the argument."""
import json, sys
from math import gcd
from fractions import Fraction
from itertools import combinations

def weights(d):
    return sorted({(a-c, b-c) for a in range(d+1) for b in range(d+1-a) for c in [d-a-b]})

def cross(u,v): return u[0]*v[1]-u[1]*v[0]
def dot(u,v): return u[0]*v[0]+u[1]*v[1]

def in_cone(x, S):
    """exact test: x in R_{>=0}-cone(S), S subset Z^2 (Caratheodory: <=2 generators)."""
    if x == (0,0): return True
    for s in S:
        if s != (0,0) and cross(s,x)==0 and dot(s,x)>0: return True
    for s1,s2 in combinations(S,2):
        D = cross(s1,s2)
        if D == 0: continue
        # x = a s1 + b s2 ; a = cross(x,s2)/D, b = cross(s1,x)/D
        a = Fraction(cross(x,s2),D); b = Fraction(cross(s1,x),D)
        if a>=0 and b>=0: return True
    return False

def rank(vecs):
    vs=[v for v in vecs if v!=(0,0)]
    if not vs: return 0
    for u,v in combinations(vs,2):
        if cross(u,v)!=0: return 2
    return 1

def kappa(S):
    """dim of cone {c>=0 : sum c_w w = 0}. P = coordinates that can be positive
    (w in P iff -w in cone(S)); the cone has a point positive on all of P, so
    dim = |P| - rank(P)."""
    S=list(S)
    P=[w for w in S if in_cone((-w[0],-w[1]),S)]
    return len(P)-rank(P)

def echelon(rows, ncols):
    """integer row echelon (Hermite-style) basis of lattice spanned by rows."""
    rows=[list(r) for r in rows]
    out=[]
    for col in range(ncols):
        piv=[r for r in rows if r[col]!=0]
        rest=[r for r in rows if r[col]==0]
        while len(piv)>1:
            piv.sort(key=lambda r: abs(r[col]))
            p=piv[0]; new=[p]
            for r in piv[1:]:
                q=r[col]//p[col]
                r2=[x-q*y for x,y in zip(r,p)]
                (new if r2[col]!=0 else rest).append(r2)
            piv=new
        if piv:
            out.append(piv[0])
        rows=rest
    return out

def order_o(S):
    """order of e3 in Z^3/M, M=<(w,1): w in S>; 0 means infinite."""
    E=echelon([(w[0],w[1],1) for w in S],3)
    for r in E:
        if r[0]==0 and r[1]==0 and r[2]!=0: return abs(r[2])
    return 0

def divisors(n): return [k for k in range(1,n+1) if n%k==0]

def hnf_lattices(maxindex):
    # rank-2 sublattices of Z^2: basis (p,0),(q,s), 0<=q<p... use column form:
    # L = {(x,y)}: generated by (p,q),(0,s) with 0<=q<s ; index p*s
    for p in range(1,maxindex+1):
        for s in range(1,maxindex//p+1):
            for q in range(s):
                yield ((p,q),(0,s))

def in_lattice(v,B):
    (p,q),(_,s)=B
    if v[0]%p: return False
    k=v[0]//p
    return (v[1]-k*q)%s==0

def in_Zv(x,v):
    if cross(x,v)!=0: return False
    i=0 if v[0]!=0 else 1
    return x[i]%v[i]==0

def candidate_sets(W):
    Wset=set(W)
    D=sorted({(u[0]-v[0],u[1]-v[1]) for u in W for v in W})
    maxc=max(max(abs(x),abs(y)) for x,y in D)
    maxindex=2*maxc*maxc   # |det| of two vectors in D is at most 2*maxc^2
    seen=set()
    # rank 0
    for w in W: seen.add(frozenset([w]))
    # rank 1: L = Z v, v nonzero in D (all multiples covered since D contains them)
    box=[(x,y) for x in range(-maxc,maxc+1) for y in range(-maxc,maxc+1)]
    for v in box:   # every possible generator of a rank-1 L(S) (superset of D)
        if v==(0,0): continue
        for w0 in W:
            S=frozenset(w for w in W if in_Zv((w[0]-w0[0],w[1]-w0[1]),v))
            seen.add(S)
    # rank 2
    for B in hnf_lattices(maxindex):
        for w0 in W:
            seen.add(frozenset(w for w in W if in_lattice((w[0]-w0[0],w[1]-w0[1]),B)))
    return seen

def compute(d):
    W=weights(d)
    cands=candidate_sets(W)
    best={}
    stats=[]
    for S in cands:
        k=kappa(S)
        if k==0: continue
        o=order_o(S)
        assert o>0, S
        for r in divisors(o):
            best[r]=max(best.get(r,0),k)
    return W,len(cands),dict(sorted(best.items()))

if __name__=="__main__":
    for d in map(int,sys.argv[1:] or [5,6,7]):
        W,n,best=compute(d)
        print(d,len(W),n,best,flush=True)
        json.dump({str(r):b for r,b in best.items()},open(f"results_d{d}.json","w"),indent=1)
